# Generated by Django 3.2.4 on 2021-08-14 23:36

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='Dni')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('fecha_nacimiento', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento')),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('N', 'No Binario')], default='F', max_length=1)),
                ('email', models.EmailField(max_length=80)),
                ('direccion', models.CharField(max_length=70, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('comorvilidades', models.BooleanField(default=False)),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
                ('creado', models.DateField(auto_now_add=True)),
                ('actualizado', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('capacidad', models.PositiveIntegerField(default=25, verbose_name='Capacidad')),
                ('virtual', models.BooleanField(default=False, verbose_name='Es virtual')),
                ('creado', models.DateField(auto_now_add=True)),
                ('actualizado', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=200, unique=True, verbose_name='Descripción')),
                ('duracion', models.PositiveIntegerField(default=5, verbose_name='Duración')),
                ('creado', models.DateField(auto_now_add=True)),
                ('actualizado', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='Dni')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('fecha_nacimiento', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento')),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('direccion', models.CharField(max_length=70, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('creado', models.DateField(auto_now_add=True)),
                ('actualizado', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null='False', unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=200, unique=True, verbose_name='Descripción')),
                ('creado', models.DateField(auto_now_add=True)),
                ('actualizado', models.DateField(auto_now=True)),
                ('carrera_nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSGAE.carrera', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=200, unique=True, verbose_name='Descripción')),
                ('anio', models.PositiveIntegerField(default=0, verbose_name='Año/Grado')),
                ('ciclo', models.CharField(choices=[('0', 'Anual'), ('1', 'Primer cuatrimestre'), ('2', 'Segundo cuatrimestre')], default='0', max_length=1)),
                ('cantidad_horas', models.PositiveIntegerField(default=0, verbose_name='Horas')),
                ('creado', models.DateField(auto_now_add=True)),
                ('actualizado', models.DateField(auto_now=True)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSGAE.nivel', verbose_name='nivel')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSGAE.profesor', verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InscripcionMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('L', 'Libre'), ('R', 'Regular')], default='R', max_length=1)),
                ('creado', models.DateField(auto_now_add=True)),
                ('actualizado', models.DateField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumno_inscrip_materia', to='appSGAE.alumno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia_inscripcion', to='appSGAE.materia')),
            ],
            options={
                'verbose_name': 'Inscripcion Materia',
                'verbose_name_plural': 'Inscripciones Materias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InscripcionCarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique_for_date='fecha', verbose_name='Fecha')),
                ('turno', models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('N', 'Noche'), ('D', 'Doble Turno')], default='M', max_length=1)),
                ('vigencia_desde', models.DateField(auto_now_add=True)),
                ('creado', models.DateField(auto_now_add=True)),
                ('actualizado', models.DateField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumno_inscrip_carrera', to='appSGAE.alumno')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSGAE.carrera')),
            ],
            options={
                'verbose_name': 'Inscripcion Carrera',
                'verbose_name_plural': 'Inscripciones Carreras',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lun', 'Lunes'), ('Mar', 'Martes'), ('Mie', 'Miercoles'), ('Jue', 'Jueves'), ('Vie', 'Viernes')], max_length=3)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('virtual', models.BooleanField(default=False, verbose_name='Es virtual')),
                ('creado', models.DateField(auto_now_add=True)),
                ('actualizado', models.DateField(auto_now=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSGAE.aula')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSGAE.materia')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['dia', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique_for_date='fecha', verbose_name='Fecha')),
                ('tipo_examen', models.CharField(choices=[('P', 'Parcial'), ('F', 'Final')], default='P', max_length=1, verbose_name='Tipo de exámen')),
                ('creado', models.DateField(auto_now_add=True)),
                ('actualizado', models.DateField(auto_now=True)),
                ('inscripcion_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Examen_insc_mat', to='appSGAE.inscripcionmateria', verbose_name='Inscripción Materia')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examenes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('presente', models.BooleanField(default=False, verbose_name='Presente')),
                ('creado', models.DateField(auto_now_add=True)),
                ('actualizado', models.DateField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Alumno_asistencia', to='appSGAE.alumno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Asistencia_materia', to='appSGAE.materia', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['id'],
            },
        ),
    ]
